services:
  backend:
    image: backend:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
  db:
    image: postgres:14.7-alpine3.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
#  frontend:
#    image: frontend:latest
#    ports:
#      - 3000:3000
#    restart: always
#    depends_on:
#      - backend