name: Deploy to Minikube

on:
  # Called from elsewhere
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_to_minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env) 
          docker build -f ./Dockerfile -t backend .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./k8s/config-map.yaml
          kubectl apply -f ./k8s/secret.yaml
          kubectl apply -f ./k8s/mysql-storage.yaml
          kubectl apply -f ./k8s/mysql-deployment.yaml
          kubectl wait --for=condition=Ready pod -l app=mysql
          sleep 5
          kubectl apply -f ./k8s/backend-deployment.yaml
          kubectl wait --for=condition=Ready pod -l app=chess-backend
          kubectl get all
      - name: Test service URLs
        run: |
          echo "CLUSTER_IP=$(kubectl get service chess-backend --output='jsonpath={.spec.clusterIPs[0]}')"
          echo "SERVICE_URL=$(minikube service chess-backend --url)"
          kubectl port-forward service/chess-backend 8080:8080 &> /dev/null &
          kubectl get pods -l app=chess-backend
          kubectl get services chess-backend
          sleep 20
          POD_NAME=$(kubectl get pods -l app=chess-backend -o jsonpath='{.items[0].metadata.name}')
          kubectl logs pod/$POD_NAME
      - run: |
          curl -l localhost:8080/health/
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete