name: Publish Image

on:
  # Called from elsewhere
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build and publish updated image
        run: |
          image_tag=rubberduck2307/${chess-backend}:latest
          docker build -f ./Dockerfile  --tag ${image_tag} .
          docker push ${image_tag}