name: Publish Image

on:
  # Called from elsewhere
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish updated image
        run: |
          reponame_lowercase=${GITHUB_REPOSITORY,,}
          image_name=$(echo ${reponame_lowercase} | cut -f2 -d/)-img
          image_tag=ghcr.io/${reponame_lowercase}/${image_name}:latest
          echo "Image tag is ${image_tag}"
          docker build -f ./Dockerfile  --tag ${image_tag} .
          docker push ${image_tag}