# A workflow for deploying the Unit Tests coverage report to GitHub Pages
name: Deploy coverage report to Pages

on:
  # Called from elsewhere
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download latest test coverage report
        uses: actions/download-artifact@v3
        with:
          name: jacoco_test_report
          path: coverage
      - name : Download latest test reports
        uses: actions/download-artifact@v3
        with:
          name: gradle-tests
          path: build/reports/tests
      - name: Setup Pages
        uses: actions/configure-pages@v3
##      - name: Upload artifact
##        uses: actions/upload-pages-artifact@v2
##        with:
#          # Upload the coverage directory from the repository
#          path: './coverage/'
      - name: Upload Gradle test reports to GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: gradle-tests
          path: build/reports/tests
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1